### ISSUE TITLE
Android adaptive icons are placed in drawable instead of mipmap

### ISSUE THREAD

**Issue by nioncode** [fluttercommunity/flutter_launcher_icons#116]
Why are adaptive icons placed in `drawable` instead of `mipmap`? Android Studio puts them into `mipmap` and all documentation says that launcher icons should go into `mipmap` instead of `drawable`.

I saw in the commits that originally the `mipmap` directory was used, but @markmooibroek changed it because of some issues (?). Could you explain which issues you saw with using mipmap?

**Comment by ghenry** [comment]
Still an issue?

**Comment by mockturtl** [comment]
https://developer.android.com/guide/practices/ui_guidelines/icon_design_adaptive

**Comment by mockturtl** [comment]
> I saw in the commits that originally the mipmap directory was used, but @markmooibroek changed it because of some issues (?).

Link?  The [blame](https://github.com/fluttercommunity/flutter_launcher_icons/blame/6658e07374527056cc1b8bc6110c56974769b214/lib/android.dart#L13) indicates they've always been `drawable`.

**Comment by mockturtl** [comment]
Confirmed `drawable` is working as intended.  `gradlew clean` seems to help flush the cache between test runs.

**Comment by davidjaldred** [comment]
Android Image Asset Studio uses mipmap for adaptive icons: https://developer.android.com/studio/write/image-asset-studio

> **Adaptive and legacy launcher icons**
[...]
Image Asset Studio places the icons in the proper locations in the `res/mipmap-density/` directories. It also creates a 512 x 512 pixel image that's appropriate for the Google Play store.

**Comment by nioncode** [comment]
> Confirmed `drawable` is working as intended. `gradlew clean` seems to help flush the cache between test runs.

Sorry, I seem to have missed these comments. Sure, `drawable` works, but it is not correct. Launcher icons should go into the `mipmap` folders and Android Studio also puts them there. Putting them into `drawable` works, but has differences in the scaling I guess (which might not be immediately noticeable). But I guess we should follow the official recommendations and not do it differently just because it also works.

**Comment by OutdatedGuy** [comment]
I asked **ChatGpt** and **Bard** about these issue and they gave the following answers:

<details><summary>ChatGPT</summary>
<p>

In Android, both the `mipmap` and `drawable` folders are used for storing different types of resources, including icons. The choice of folder depends on the purpose and usage of the icons.

1. `mipmap` folder:
The `mipmap` folder is primarily used for storing app launcher icons. These icons are adaptive launcher icons that can automatically adjust their appearance based on the device's display density. Adaptive icons were introduced in Android 8.0 (API level 26) and provide better visual consistency across different devices.

The `mipmap` folder has different density-specific subfolders, such as `mipmap-mdpi`, `mipmap-hdpi`, `mipmap-xhdpi`, `mipmap-xxhdpi`, `mipmap-xxxhdpi`, etc. Each subfolder should contain launcher icons with the corresponding density.

Place the adaptive launcher icons in the appropriate `mipmap` subfolders. Android will automatically choose the appropriate icon based on the device's screen density.

2. `drawable` folder:
The `drawable` folder is used for storing other types of drawables, including icons that are not specifically designed for the launcher. Legacy icons, or non-adaptive icons, should be placed in the `drawable` folder.

Legacy icons are the ones designed for older versions of Android, prior to the introduction of adaptive icons. These icons do not automatically adapt to different screen densities. If your app targets Android 7.1 (API level 25) or below, you may need to provide legacy icons.

Place the legacy icons in the appropriate `drawable` subfolders based on the density, such as `drawable-mdpi`, `drawable-hdpi`, `drawable-xhdpi`, `drawable-xxhdpi`, `drawable-xxxhdpi`, etc. Each subfolder should contain icons with the corresponding density.

It's worth noting that if your app targets Android 8.0 (API level 26) or higher, it is recommended to use adaptive launcher icons and place them in the `mipmap` folder. However, you can still provide legacy icons in the `drawable` folder for backward compatibility with older devices.

To summarize:
- Adaptive launcher icons: Place them in the appropriate density-specific `mipmap` subfolders.
- Legacy icons: Place them in the appropriate density-specific `drawable` subfolders.

By organizing your icons in this way, you ensure that your app displays the appropriate icons on devices with different screen densities and maintains compatibility with older Android versions.

</p>
</details> 

<details><summary>Bard</summary>
<p>

<p style="margin: 0px 0px 24px; white-space: pre-wrap; word-break: break-word; color: rgb(227, 227, 227); font-family: &quot;Google Sans&quot;, &quot;Helvetica Neue&quot;, sans-serif; font-size: 16px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(19, 19, 20); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">Adaptive launcher icons should be placed in the <code style="font-size: 0.875rem; font-weight: 400; line-height: 1.25rem; letter-spacing: normal; font-family: &quot;Google Sans Mono&quot;, monospace; color: var(--bard-color-on-surface-variant); background-color: var(--bard-color-surface-container-high); border-radius: 6px; padding: 1px 6px;">mipmap</code> folder, specifically in the <code style="font-size: 0.875rem; font-weight: 400; line-height: 1.25rem; letter-spacing: normal; font-family: &quot;Google Sans Mono&quot;, monospace; color: var(--bard-color-on-surface-variant); background-color: var(--bard-color-surface-container-high); border-radius: 6px; padding: 1px 6px;">mipmap-anydpi-v26</code> directory. This is because adaptive icons were introduced in API level 26, and the <code style="font-size: 0.875rem; font-weight: 400; line-height: 1.25rem; letter-spacing: normal; font-family: &quot;Google Sans Mono&quot;, monospace; color: var(--bard-color-on-surface-variant); background-color: var(--bard-color-surface-container-high); border-radius: 6px; padding: 1px 6px;">mipmap</code> folder is used for resources that should be available on all devices, regardless of their screen density.</p><p style="margin: 24px 0px; white-space: pre-wrap; word-break: break-word; color: rgb(227, 227, 227); font-family: &quot;Google Sans&quot;, &quot;Helvetica Neue&quot;, sans-serif; font-size: 16px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(19, 19, 20); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">Legacy icons, on the other hand, should be placed in the <code style="font-size: 0.875rem; font-weight: 400; line-height: 1.25rem; letter-spacing: normal; font-family: &quot;Google Sans Mono&quot;, monospace; color: var(--bard-color-on-surface-variant); background-color: var(--bard-color-surface-container-high); border-radius: 6px; padding: 1px 6px;">drawable</code> folder. Legacy icons are those that do not support adaptive icons, and they will be used on devices that are running API level 25 or lower.</p><p style="margin: 24px 0px; white-space: pre-wrap; word-break: break-word; color: rgb(227, 227, 227); font-family: &quot;Google Sans&quot;, &quot;Helvetica Neue&quot;, sans-serif; font-size: 16px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(19, 19, 20); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">Here is a table that summarizes which icons should be placed in which folder:</p><div class="horizontal-scroll-wrapper" style="overflow-x: scroll; color: rgb(227, 227, 227); font-family: &quot;Google Sans&quot;, &quot;Helvetica Neue&quot;, sans-serif; font-size: 16px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; background-color: rgb(19, 19, 20); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><div class="table-block-component" style="overflow: scroll hidden;">

Icon type | Folder
-- | --
Adaptive icon | mipmap-anydpi-v26
Legacy icon | drawable

</div><div _ngcontent-ng-c1335972230="" class="table-footer ng-star-inserted" style="display: flex; -webkit-box-pack: end; justify-content: flex-end; -webkit-box-align: center; align-items: center; background-color: var(--bard-color-inverse-on-surface); padding-right: 8px; border-top: 1px solid var(--bard-color-outline-variant);"><button _ngcontent-ng-c1335972230="" mat-button="" mattooltip="Export table to Sheets" class="mat-mdc-tooltip-trigger export-sheets-button-wrapper mdc-button mat-mdc-button gmat-mdc-button-with-prefix mat-unthemed mat-mdc-button-base gmat-mdc-button" mat-ripple-loader-uninitialized="" mat-ripple-loader-class-name="mat-mdc-button-ripple" jslog="184701;track:generic_click,impression;BardVeMetadataKey:[[&quot;r_46acecbab5f0bc29&quot;,&quot;c_be2f03338fd55bcd&quot;]]" aria-describedby="cdk-describedby-message-ng-1-22" cdk-describedby-host="ng-1" style="--mat-mdc-button-persistent-ripple-color: #e8eaed; --mat-mdc-button-ripple-color: rgba(232,234,237,0.1); -webkit-font-smoothing: antialiased; font-family: &quot;Google Sans&quot;, Roboto, Arial, sans-serif; font-size: 0.875rem; line-height: var(--mdc-typography-button-line-height,1.25rem); font-weight: 500; letter-spacing: 0.0107143em; text-decoration: var(--mdc-typography-button-text-decoration,none); text-transform: none; position: relative; display: inline-flex; align-items: center; justify-content: center; box-sizing: border-box; min-width: 64px; border: none; outline: none; user-select: none; appearance: none; overflow: visible; vertical-align: middle; background: rgba(0, 0, 0, 0); padding: 0px 8px; height: 36px; border-radius: var(--mdc-text-button-container-shape, var(--mdc-shape-small, 4px)); -webkit-tap-highlight-color: rgba(0, 0, 0, 0); --mdc-text-button-label-text-color: #e8eaed; color: var(--mdc-text-button-label-text-color, inherit);"><span class="mat-mdc-button-persistent-ripple mdc-button__ripple" style="border-radius: inherit; inset: 0px; position: absolute; pointer-events: none; height: 36px; overflow: hidden; width: 160.055px; z-index: 0;"></span><span class="mdc-button__label" style="position: relative; z-index: 1;"><span _ngcontent-ng-c1335972230="" class="export-sheets-button" style="display: flex; -webkit-box-pack: center; justify-content: center; -webkit-box-align: center; align-items: center;"><span _ngcontent-ng-c1335972230="" class="export-sheets-icon" style="padding-top: 5.5px; margin-right: 8px;"><mat-icon _ngcontent-ng-c1335972230="" role="img" class="mat-icon notranslate google-symbols mat-icon-no-color" aria-hidden="true" data-mat-icon-type="font" style="font-family: &quot;Google Symbols&quot;; font-weight: normal; font-style: normal; font-size: 24px; line-height: 1; letter-spacing: normal; text-transform: none; display: inline-block; white-space: nowrap; overflow-wrap: normal; direction: ltr; font-feature-settings: &quot;liga&quot;; -webkit-font-smoothing: antialiased; user-select: none; background-repeat: no-repeat; fill: currentcolor; height: 24px; width: 24px; overflow: hidden;">drive_spreadsheet</mat-icon></span><span _ngcontent-ng-c1335972230="">Export to Sheets</span></span></span><span class="mat-mdc-focus-indicator" style="position: absolute; inset: 0px;"></span><span class="mat-mdc-button-touch-target" style="position: absolute; top: 18px; height: 48px; left: 0px; right: 0px; transform: translateY(-50%);"></span></button></div></div></table-block></div></div><p style="margin: 24px 0px; white-space: pre-wrap; word-break: break-word; color: rgb(227, 227, 227); font-family: &quot;Google Sans&quot;, &quot;Helvetica Neue&quot;, sans-serif; font-size: 16px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(19, 19, 20); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">Here are some additional details about the <code style="font-size: 0.875rem; font-weight: 400; line-height: 1.25rem; letter-spacing: normal; font-family: &quot;Google Sans Mono&quot;, monospace; color: var(--bard-color-on-surface-variant); background-color: var(--bard-color-surface-container-high); border-radius: 6px; padding: 1px 6px;">mipmap</code> and <code style="font-size: 0.875rem; font-weight: 400; line-height: 1.25rem; letter-spacing: normal; font-family: &quot;Google Sans Mono&quot;, monospace; color: var(--bard-color-on-surface-variant); background-color: var(--bard-color-surface-container-high); border-radius: 6px; padding: 1px 6px;">drawable</code> folders:</p><ul style="margin: 4px 0px; padding-inline-start: 36px; color: rgb(227, 227, 227); font-family: &quot;Google Sans&quot;, &quot;Helvetica Neue&quot;, sans-serif; font-size: 16px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; background-color: rgb(19, 19, 20); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><li style="margin-bottom: 10px;">The<span> </span><code style="font-size: 0.875rem; font-weight: 400; line-height: 1.25rem; letter-spacing: normal; font-family: &quot;Google Sans Mono&quot;, monospace; color: var(--bard-color-on-surface-variant); background-color: var(--bard-color-surface-container-high); border-radius: 6px; padding: 1px 6px;">mipmap</code><span> </span>folder is used for resources that should be available on all devices, regardless of their screen density. This is done by providing different versions of the resource for different screen densities. For example, there might be a<span> </span><code style="font-size: 0.875rem; font-weight: 400; line-height: 1.25rem; letter-spacing: normal; font-family: &quot;Google Sans Mono&quot;, monospace; color: var(--bard-color-on-surface-variant); background-color: var(--bard-color-surface-container-high); border-radius: 6px; padding: 1px 6px;">mipmap-hdpi</code><span> </span>directory for high-density screens, a<span> </span><code style="font-size: 0.875rem; font-weight: 400; line-height: 1.25rem; letter-spacing: normal; font-family: &quot;Google Sans Mono&quot;, monospace; color: var(--bard-color-on-surface-variant); background-color: var(--bard-color-surface-container-high); border-radius: 6px; padding: 1px 6px;">mipmap-mdpi</code><span> </span>directory for medium-density screens, and so on.</li><li style="margin-bottom: 10px;">The<span> </span><code style="font-size: 0.875rem; font-weight: 400; line-height: 1.25rem; letter-spacing: normal; font-family: &quot;Google Sans Mono&quot;, monospace; color: var(--bard-color-on-surface-variant); background-color: var(--bard-color-surface-container-high); border-radius: 6px; padding: 1px 6px;">drawable</code><span> </span>folder is used for resources that do not need to be available on all devices. This is because the resources in the<span> </span><code style="font-size: 0.875rem; font-weight: 400; line-height: 1.25rem; letter-spacing: normal; font-family: &quot;Google Sans Mono&quot;, monospace; color: var(--bard-color-on-surface-variant); background-color: var(--bard-color-surface-container-high); border-radius: 6px; padding: 1px 6px;">drawable</code><span> </span>folder are not scaled to different screen densities.</li></ul><p style="margin: 24px 0px; white-space: pre-wrap; word-break: break-word; color: rgb(227, 227, 227); font-family: &quot;Google Sans&quot;, &quot;Helvetica Neue&quot;, sans-serif; font-size: 16px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(19, 19, 20); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">I hope this helps! Let me know if you have any other questions.</p>

</p>
</details>

**Comment by islandYzx** [comment]
As an Android developer with a little OCD, placed the adaptive icons in drawable is different with AS which make me feel uncomfortable. I can't accept it.

**Comment by MarkOSullivan94** [comment]
In the official Android code lab for setting the launcher icon you can see they specify it to be in the mipmap folders

<img width="1728" alt="Screenshot 2024-09-21 at 10 41 59" src="https://github.com/user-attachments/assets/83dfea08-d474-488b-afe8-e95de45d9e6c">

In the following step from the same code lab for setting up your app to have adaptive icons you need to have the foreground and background in the drawable folder

<img width="1728" alt="Screenshot 2024-09-21 at 10 39 30" src="https://github.com/user-attachments/assets/6d11b72f-cdf0-4501-9cf5-fb4fe1b8bef2">

Source: https://developer.android.com/codelabs/basic-android-kotlin-compose-training-change-app-icon#2

It's been so long since I used the Android Studio asset generator to recall whether or not they place the foreground and background for adaptive icons into the mipmap folder but if they do then it's going against the Android team's recommendation

**Comment by Levi-Lesches** [comment]
@MarkOSullivan94 The official Android docs seem to have been updated

https://developer.android.com/training/multiscreen/screendensities#mipmap

> **Put app icons in mipmap directories**
> As with other bitmap assets, you need to provide density-specific versions of your app icon. However, some app launchers display your app icon as much as 25% larger than what's called for by the device's density bucket.
> 
> For example, if a device's density bucket is xxhdpi and the largest app icon you provide is in drawable-xxhdpi, the app launcher scales up this icon, which makes it appear less crisp.
> 
> To avoid this, put all your app icons in mipmap directories instead of drawable directories. Unlike drawable directories, all mipmap directories are retained in the APK, even if you build density-specific APKs. This lets launcher apps pick the best resolution icon to display on the home screen.
