### ISSUE TITLE
Adaptive icon issue

### ISSUE THREAD

**Issue by wmla419** [fluttercommunity/flutter_launcher_icons#132]
`* What went wrong:
Execution failed for task ':app:mergeDebugResources'.
> java.util.concurrent.ExecutionException: com.android.builder.internal.aapt.v2.Aapt2Exception: Android resource compilation failed
  C:\Users\test\Documents\GitHub\test\android\app\src\main\res\values\colors.xml:3:5-78: AAPT: error: invalid color.

Gradle task assembleDebug failed with exit code 1`

I keep receiving this error after I tried to use adaptive icon, when I try to change back to non-adaptive icon, same error popped up also.

**Comment by yaizudamashii** [comment]
This problem happens because we are using an image as adaptive image background, and somehow that is interpreted as colors.  Frankly this package does not work for adaptive icons.  We have to go into android directory and handle the images and res/mipmap-anydpi-v26/ic_launcher.xml ourselves.
The link to adaptive icons here
https://developer.android.com/guide/practices/ui_guidelines/icon_design_adaptive

**Comment by Ahmadre** [comment]
eeehm...

![Bildschirmfoto 2021-09-10 um 15 38 41](https://user-images.githubusercontent.com/18512224/132862263-ccfab6e6-dcf6-4e62-ae18-421074ebd75c.png)

**Comment by Ahmadre** [comment]
@MarkOSullivan94
