### ISSUE TITLE
Launcher Icons not showing for android 

### ISSUE THREAD

**Issue by LenvZyl** [fluttercommunity/flutter_launcher_icons#137]
![flutter Icons](https://user-images.githubusercontent.com/20842612/69123601-79a81c80-0aaa-11ea-9784-98e4e7e7cc3d.png)

Here you can see I ran
flutter pub get
flutter pub run flutter_launcher_icons:main

It created the mipmap images, but the Icons are still not showing
Currently, my app does not have an Icon at all and there is no where to open the app
App can only open by "flutter run"

**Comment by LenvZyl** [comment]
![flutter doctor](https://user-images.githubusercontent.com/20842612/69123876-26829980-0aab-11ea-9312-02dd3b5576e0.png)

**Comment by athilams** [comment]
I have the exact same issue. It creates the images, but the app has no icon and therefore I cannot open it in any other way rather than using "flutter run". In iOS it works fine, though. 

Steps:

Added the dependency under dev_dependencies
Ran "flutter pub get"
Then "flutter pub pub run flutter_launcher_icons:main"
Then "flutter clean"
And finally "flutter run"

Also tried some of the steps in different order, no success. App runs fine.

Flutter doctor output: 

[✓] Flutter (Channel stable, v1.12.13+hotfix.7, on Linux, locale en_US.UTF-8)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.1)
[✓] Android Studio (version 3.4)
[✓] VS Code (version 1.42.1)
[✓] Connected device (1 available)

• No issues found!

**Comment by LenvZyl** [comment]
My `ic_launcher` was incorrectly named in the AndroidManifest.xml
```
<application
        android:name="io.flutter.app.FlutterApplication"
        android:label="App name"
        android:icon="@mipmap/ic_launcher"
```

**Comment by athilams** [comment]
Thank you for your response. I'll try this solution right away.

**Comment by athilams** [comment]
Could you please explain what especifically you changed in the AndroidManifest? The icon still does not show up.  It doesn't seem to be wrongly named.

**Comment by SwiftyFlow** [comment]
More for me for the next time I have this (2nd app, 2nd time...) In android > app > src > main > AndroidManifest.xml: 

''' <activity
            android:name=".MainActivity"
            android:exported="true"
            android:launchMode="singleTop"
            android:theme="@style/LaunchTheme"
            android:configChanges="orientation|keyboardHidden|keyboard|screenSize|smallestScreenSize|locale|layoutDirection|fontScale|screenLayout|density|uiMode"
            android:hardwareAccelerated="true"
            android:windowSoftInputMode="adjustResize">
            
            <meta-data
              android:name="io.flutter.embedding.android.NormalTheme"
              android:resource="@style/NormalTheme"
              />
            <intent-filter>
                <action android:name="android.intent.action.MAIN"/>
                <category android:name="android.intent.category.LAUNCHER"/>
            </intent-filter>
        </activity>'''

android:name="io.flutter.embedding.android.NormalTheme" MUST BE kept as is. It's referencing Flutter for some magic to happen behind the scene...
