### ISSUE TITLE
In recent apps list, Android icon is displayed instead of the app icon

### ISSUE THREAD

**Issue by dev-aentgs** [fluttercommunity/flutter_launcher_icons#167]
### :information_source: Info

Version: `^0.7.3`

### :speech_balloon: Description

In **recent apps list**, Android icon is displayed instead of the app icon. 
Tested on physical device Nokia 6.1
Android Q version 10 

### :scroll: Pubspec.yaml

Uploading pubspec as txt here
[pubspec.txt](https://github.com/fluttercommunity/flutter_launcher_icons/files/4610361/pubspec.txt)

**Comment by ghenry** [comment]
Try with `android: true`

**Comment by lautaropaske** [comment]
Can confirm this is happening on Android 10. Having the same issue there while it displays perfectly on Android 8 (both tested in emulators)

**Comment by YehudaKremer** [comment]
I was able to solve by deleting the app storage and cache:
![Capture](https://user-images.githubusercontent.com/946652/87486230-7f5aff80-c643-11ea-83ce-ea1f7bbf87fc.PNG)

**Comment by AldrinMathew** [comment]
In my case (`Android 10`) this happens when the icon is a PNG with transparent pixels. When there were no transparent pixels, the entire icon was squeezed down to be fitting inside the circle.
And uninstalling the app, cleaning the cache, rerunning `flutter pub run flutter_launcher_icons:main -f pubspec.yaml` and then installing it again didn't solve the issue
