### ISSUE TITLE
iOS Icons Not Valid - Generated with transparency which is not allowed

### ISSUE THREAD

**Issue by cliffordh** [fluttercommunity/flutter_launcher_icons#172]
### :information_source: Info

Version: 0.7.5

### :speech_balloon: Description

Receiving an error when attempting to validate my app during submission to App Store Connect.
"Invalid App Store Icon. The App Store Icon in the asset catalog in 'Runner.app' can't be transparent nor contain an alpha channel."

### :scroll: Pubspec.yaml
Relevant portion of pubspec.yaml
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.7.5
  flutter_native_splash: ^0.1.9

flutter_icons:
  image_path: "assets/icon512.png"
  android: true
  ios: true

![image](https://user-images.githubusercontent.com/1755156/82331268-e21c7b80-99b1-11ea-8f5f-61e8842e255d.png)

**Comment by cliffordh** [comment]
Note, source icon PNG does NOT have transparency or an alpha channel.

**Comment by cliffordh** [comment]
SOLVED. Still a bug imo... if the source image is 512x512 and not 1024x1024 then flutter_launcher_icons generates a 1024 app asset which has transparency. Using an original 1024x1024 image without transparency works.

**Comment by liudonghua123** [comment]
I have the same issue, can we process the icon within this package?

![image](https://user-images.githubusercontent.com/2276718/84349539-1cacb900-abea-11ea-8ecb-7366d1ab872f.png)

**Comment by TahaAli07** [comment]
Basically the issue is that the png used as an icon contains transparent background

Use this tool to remove transparent areas - https://onlinepngtools.com/fill-transparent-png-pixels

After that - 

1. Add flutter_launcher_icons Plugin to pubspec.yaml
e.g.
```

dev_dependencies: 
  flutter_test:
    sdk: flutter

  flutter_launcher_icons: ^0.7.5

flutter_icons:
  image_path: "icon/icon.png" 
  android: true
  ios: true
```
2. Prepare an app icon for the specified path. e.g. icon/icon.png
3. Execute command on the terminal to Create app icons:
$ flutter pub get

$ flutter pub pub run flutter_launcher_icons:main

This last command is extremely important , just running pub get somehow doses't generate new icons.

**Comment by softmarshmallow** [comment]
just to be sure, use jpg -> always works
or use png (in photoshop or other tools select "exclude alpha channel")

**Comment by fedotxxl** [comment]
Is it possible to make WARN message on generation?

**Comment by yourshinsuke** [comment]
only fix one original file works?

**Comment by yourshinsuke** [comment]
hmmmm.
I should set all files of `ios/Runner/Assets.xcassets/AppIcon.appiconset`???
I guess it is trouble some

**Comment by yourshinsuke** [comment]
open original png file by `Preview` app.
and `File => Export... => uncheck "Alpha"`

**Comment by yourshinsuke** [comment]
I hope it automatically by the tool. Can you?

**Comment by sebastianbuechler** [comment]
This issue is still present but can be solved by using a 1024 by 1024 pixel png or jpg file. 

I would suggest to either make a quick fix by checking the resolution of the input and give a warning if the resolution does not fit (otherwise the user will have a problem with the app store). Or if possible do an automatic conversion within the tool. However, I guess that would take more time to implement.

**Comment by irajeshh** [comment]
Note: ⚠️ I didn't read the solutions provided below that 1024x1024 answer.

Tried the 1024x1024 size, but did't solved the issue.
So I used this old [app](https://alphachannelremover.blogspot.com) to remove alpha channel & transparency.

Drag & Drop All the Images to the above app, it will do the magic & this time my archive is successfully uploaded.
![image](https://user-images.githubusercontent.com/85046336/229800965-dd6241e0-a62b-4188-a650-01c1a2abb7af.png)
