### ISSUE TITLE
[BUG] in flutter_launcher_icons/utils.dart at createResizedImage (image.width) width was called on null

### ISSUE THREAD

**Issue by SamerOrfali** [fluttercommunity/flutter_launcher_icons#220]
### :information_source: Info
version of the package --->0.8.1

### :speech_balloon: Description
Enter a description of your problem here

NoSuchMethodError: The getter 'width' was called on null.
Receiver: null
Tried calling: width
#0      Object.noSuchMethod (dart:core-patch/object_patch.dart:51:5)
#1      createResizedImage (package:flutter_launcher_icons/utils.dart:4:13)
#2      overwriteExistingIcons (package:flutter_launcher_icons/android.dart:225:25)
#3      createDefaultIcons (package:flutter_launcher_icons/android.dart:49:7)
#4      createIconsFromConfig (package:flutter_launcher_icons/main.dart:99:5)
#5      createIconsFromArguments (package:flutter_launcher_icons/main.dart:58:7)
#6      main (file:///C:/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_launcher_icons-0.8.1/bin/main.dart:6:3)
#7      _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:299:32)
#8      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:168:12)

### :scroll: Pubspec.yaml

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_launcher_icons: ^0.8.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter_icons:
    android: true
    ios: true
    image_path: "assets/images/app_icon.svg"

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/images/icons/

**Comment by TheWithz** [comment]
I have the same error. 
Here's my pubspec.yaml

> environment:
>   sdk: ">=2.7.0 <3.0.0"

> dependencies:
>   flutter_launcher_icons: "^0.8.0"
>   flutter:
>     sdk: flutter

> dev_dependencies:
>   flutter_test:
>     sdk: flutter

> flutter:
>   uses-material-design: true
>   fonts:
>     - family:  GardenPlannerIcons
>       fonts:
>         - asset: fonts/GardenPlannerIcons.ttf

> flutter_icons:
>   android: "launcher_icon"
>   adaptive_icon_background: #FF4CAF50
>   ios: false
>   image_path: "assets/icon/garden_planner.ico"

**Comment by TheWithz** [comment]
@SamerOrfali I was able to solve this in #196 due to some missing quotes. 

looks like you're missing quotes around the flutter_launcher_icons: version number

**Comment by johnshiver** [comment]
ℹ️ Info
version of the package --->0.8.0

💬 Description
  ════════════════════════════════════════════
     FLUTTER LAUNCHER ICONS (v0.8.0)                               
  ════════════════════════════════════════════
  
• Creating default icons Android
• Overwriting the default Android launcher icon with a new icon

✓ Successfully generated launcher icons
Unhandled exception:
NoSuchMethodError: The getter 'width' was called on null.
Receiver: null
Tried calling: width
#0      Object.noSuchMethod (dart:core-patch/object_patch.dart:51:5)
#1      createResizedImage (package:flutter_launcher_icons/utils.dart:4:13)
#2      overwriteExistingIcons (package:flutter_launcher_icons/android.dart:225:25)
#3      createDefaultIcons (package:flutter_launcher_icons/android.dart:49:7)
#4      createIconsFromConfig (package:flutter_launcher_icons/main.dart:99:5)
#5      createIconsFromArguments (package:flutter_launcher_icons/main.dart:58:7)
#6      main (file:///Users/jshiver/dev/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_launcher_icons-0.8.1/bin/main.dart:6:3)
#7      _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:299:32)
#8      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:168:12)
pub finished with exit code 255


📜 Pubspec.yaml
environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  provider: "^4.0.0"
  toggle_switch: "^0.1.4"
  percent_indicator: "^2.1.5"
  charts_flutter: "^0.9.0"
  http: "^0.12.0+2"
  shared_preferences: ">=0.5.3+1 <2.0.0"
  dio: "3.0.9"
  flutter_login: ^1.0.14
  flutter_secure_storage: ^3.3.5
  liquid_pull_to_refresh: ^2.0.0
  flutter_spinkit: "^4.1.2"
  flutter_native_timezone: "1.0.4"
  audioplayers: 0.17.0
  package_info: ^0.4.0+16


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.8.1"

flutter_icons:
  image_path: "assets/timer.svg"
  android: true
  ios: true
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/timer_transparent.svg"


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/

**Comment by kinafu** [comment]
I believe the problem is because currently `.svg` files are not supported.
See [https://github.com/fluttercommunity/flutter_launcher_icons/issues/20](Issue #20)

**Comment by RatakondalaArun** [comment]
Closing this as inactive in case this issue still exists please open a new issue
