### ISSUE TITLE
xml out-of-date and conflict with other newer lib

### ISSUE THREAD

**Issue by jinfagang** [fluttercommunity/flutter_launcher_icons#234]
```
Because no versions of flutter_svg match >0.20.0-nullsafety.3 <0.21.0 and flutter_svg 0.20.0-nullsafety.3 depends on xml ^5.0.0-nullsafety.0, flutter_svg ^0.20.0-nullsafety.3 requires xml ^5.0.0-nullsafety.0.
Because image >=2.1.14 <3.0.0-nullsafety.0 depends on xml ^4.2.0 and image >=2.0.6 <2.1.14 depends on xml ^3.2.5, image >=2.0.6 <3.0.0-nullsafety.0 requires xml ^3.2.5 or ^4.2.0.
Thus, flutter_svg ^0.20.0-nullsafety.3 is incompatible with image >=2.0.6 <3.0.0-nullsafety.0.
And because flutter_launcher_icons >=0.7.1 depends on image ^2.1.1, flutter_svg ^0.20.0-nullsafety.3 is incompatible with flutter_launcher_icons >=0.7.1.
So, because flutter_app depends on both flutter_launcher_icons ^0.8.1 and flutter_svg ^0.20.0-nullsafety.3, version solving failed.
Running "flutter pub get" in daybreak_flutter...                        
pub get failed (1; So, because flutter_app depends on both flutter_launcher_icons ^0.8.1 and
flutter_svg ^0.20.0-nullsafety.3, version solving failed.)
```

**Comment by m7mdra** [comment]
Same issue here. since its a dev dependencies i will remove it for now.

**Comment by MarkOSullivan94** [comment]
Could you try again with v0.9.0?

**Comment by Niko-by** [comment]
> Released v0.9.0 yesterday which upgraded the dependency versions, feel free to give it a try and let me know if you're still having issues.

I have version 0.9.0 and flutter_svg also updated to the latest version 0.19.3 but I still get this error.

`Running "flutter pub get" in savetik...                         
Because image >=3.0.1 depends on xml ^5.0.0 and image >=3.0.0-nullsafety.0 <3.0.1 depends on xml ^5.0.0-nullsafety.1, image >=3.0.0-nullsafety.0 requires xml ^5.0.0-nullsafety.1.
And because flutter_launcher_icons >=0.9.0 depends on image ^3.0.0-nullsafety.0, flutter_launcher_icons >=0.9.0 requires xml ^5.0.0-nullsafety.1.
And because flutter_svg 0.19.3 depends on xml ^4.2.0 and no versions of flutter_svg match >0.19.3 <0.20.0, flutter_launcher_icons >=0.9.0 is incompatible with flutter_svg ^0.19.3.
So, because savetik depends on both flutter_svg ^0.19.3 and flutter_launcher_icons ^0.9.0, version solving failed.`

**Comment by diazsasak** [comment]
Hi everyone. i want to report me also still got error using version 0.9.0

`Because image >=3.0.1 depends on xml ^5.0.0 and image >=3.0.0-nullsafety.0 <3.0.1 depends on xml ^5.0.0-nullsafety.1, image >=3.0.0-nullsafety.0 requires xml ^5.0.0-nullsafety.1.
And because flutter_launcher_icons >=0.9.0 depends on image ^3.0.0-nullsafety.0 and flutter_svg >=0.18.1 <0.20.0-nullsafety.0 depends on xml ^4.2.0, flutter_launcher_icons >=0.9.0 is incompatible with flutter_svg >=0.18.1 <0.20.0-nullsafety.0.
So, because route_tracking_mobile depends on both flutter_svg ^0.19.3 and flutter_launcher_icons ^0.9.0, version solving failed.
Running "flutter pub get" in route_tracking_mobile...                   
pub get failed (1; So, because route_tracking_mobile depends on both flutter_svg ^0.19.3 and flutter_launcher_icons ^0.9.0, version solving failed.)`

**Comment by MarkOSullivan94** [comment]
Upgraded dependencies in the latest version (v0.9.1), try updating and if it still persists, take a look at this: https://github.com/fluttercommunity/flutter_launcher_icons/blob/master/README.md#dependency-incompatible
