### ISSUE TITLE
[BUG] Resolving Dependencies Fail

### ISSUE THREAD

**Issue by sfmsakib** [fluttercommunity/flutter_launcher_icons#241]
Because flutter_launcher_icons >=0.9.0 depends on args 2.0.0 and every version of flutter_driver from sdk depends on args 1.6.0, flutter_launcher_icons >=0.9.0 is incompatible with flutter_driver from sdk.

**Comment by tobylewis** [comment]
I'm getting the same issue.  I'm running on stable channel, and can get the 0.8.1 version loaded but not the 0.9.0.  However when I do get 0.8.1 it won't run complaining the SDK is not the right version. running pub get does not clear the issue.


dev_dependencies:
  flutter_driver:
    sdk: flutter
  flutter_test:
    sdk: flutter
  integration_test: ^1.0.0
  flutter_launcher_icons: "^0.9.0"


Because flutter_launcher_icons >=0.9.0 depends on args 2.0.0 and every version of flutter_driver from sdk depends on args 1.6.0, flutter_launcher_icons >=0.9.0 is incompatible with flutter_driver from sdk.
So, because time_pie_02 depends on both flutter_driver any from sdk and flutter_launcher_icons ^0.9.0, version solving failed.

dev_dependencies:
  flutter_driver:
    sdk: flutter
  flutter_test:
    sdk: flutter
  integration_test: ^1.0.0
  flutter_launcher_icons: "^0.8.1"


Atlas:time_pie_02 tobylewis$ flutter pub get
Running "flutter pub get" in time_pie_02...                        629ms

Atlas:time_pie_02 tobylewis$ pub run flutter_launcher_icons:main
Dart 2.10.4 is incompatible with your dependencies' SDK constraints. Please run "pub get" again.

Atlas:time_pie_02 tobylewis$ dart --version
Dart SDK version: 2.12.1 (stable) (Wed Mar 10 10:18:47 2021 +0100) on "macos_x64"

Atlas:time_pie_02 tobylewis$ flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 2.0.2, on macOS 11.2.3 20D91 darwin-x64, locale en-GB)
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
[✓] Xcode - develop for iOS and macOS
[✓] Chrome - develop for the web
[✓] Android Studio (version 4.1)
[✓] VS Code (version 1.54.3)
[✓] Connected device (3 available)

• No issues found!
Atlas:time_pie_02 tobylewis$

**Comment by tsinis** [comment]
As a quick fix: since both flutter_driver and flutter_launcher_icons are both dev dependencies, you can just comment out flutter_driver during icon creation and restore after icon creation is complete, then you can obviously comment out flutter_launcher_icons and uncomment flutter_driver again.

**Comment by alexobviously** [comment]
`Because every version of audio_service from git depends on flutter_cache_manager ^3.0.1 and no versions of flutter_cache_manager match >3.0.1 <4.0.0, every version of audio_service from git requires flutter_cache_manager 3.0.1.
And because flutter_cache_manager 3.0.1 depends on image ^3.0.1 and flutter_launcher_icons >=0.7.1 <0.9.0 depends on image ^2.1.1, audio_service from git is incompatible with flutter_launcher_icons >=0.7.1 <0.9.0.`

Me too

**Comment by ncuillery** [comment]
Any update on this?

I believe #245 is related to this issue.

**Comment by mregnauld** [comment]
+1 This bug is quite annoying, any update?

**Comment by alek-tech** [comment]
I'm getting this error:

Because archive >=3.0.0-nullsafety.0 <3.0.0 depends on crypto ^3.0.0-nullsafety.0 and image >=3.0.0-nullsafety.0 <3.0.1 depends on archive ^3.0.0-nullsafety.0, image >=3.0.0-nullsafety.0 <3.0.1 requires crypto ^3.0.0-nullsafety.0 or archive ^3.0.0.
And because flutter_launcher_icons >=0.9.0 <0.9.1 depends on image ^3.0.0-nullsafety.0 and flutter_launcher_icons >=0.9.1 <0.12.0 depends on image ^3.0.2, flutter_launcher_icons >=0.9.0 <0.12.0 requires crypto ^3.0.0-nullsafety.0 or archive ^3.0.0 or image ^3.0.1.
And because image >=3.0.1 <3.1.0 depends on archive ^3.0.0 and image >=3.1.0 depends on archive ^3.1.2, flutter_launcher_icons >=0.9.0 <0.12.0 requires crypto ^3.0.0-nullsafety.0 or archive ^3.0.0.
And because archive >=3.0.0 depends on crypto ^3.0.0 and uuid 2.0.0 depends on crypto ^2.0.0, uuid 2.0.0 is incompatible with flutter_launcher_icons >=0.9.0 <0.12.0.
So, because wheretolook depends on both uuid 2.0.0 and flutter_launcher_icons ^0.9.0, version solving failed.
pub get failed
command: "D:\flutter_windows_3.7.3-stable\flutter\bin\cache\dart-sdk\bin\dart __deprecated_pub --directory . get --example"
pub env: {
  "FLUTTER_ROOT": "D:\flutter_windows_3.7.3-stable\flutter",
  "PUB_ENVIRONMENT": "flutter_cli:get",
  "PUB_CACHE": "C:\Users\alek\AppData\Local\Pub\Cache",
}
exit code: 1
