### ISSUE TITLE
[FEATURE REQUEST] Add warning if config file isnt located next to pubspec.yaml directory

### ISSUE THREAD

**Issue by apgapg** [fluttercommunity/flutter_launcher_icons#257]
### :speech_balloon: Description
I placed all my launcher icon config files in a dir named `launcher_icon/` due to which flavors weren't respected.
After struggle, I saw a note in README to place it within the same dir as of `pubspec.yaml`.

Can we add a warning in console stating to put config file besides pubspec so as to prevent errors for future developers?

**Comment by timbrueckner** [comment]
I think, this issue was fixed with https://github.com/fluttercommunity/flutter_launcher_icons/pull/398. If the plugin does not find a config file, it now hints to use the `--file` option in order to point to the config.


> ✗ ERROR: NoConfigFoundException 
No configuration found in flutter_launcher_icons.yaml or in pubspec.yaml. In case file exists in different directory use --file option
