### ISSUE TITLE
[FEATURE REQUEST] Support for android 13 themed icons

### ISSUE THREAD

**Issue by guy-evdev** [fluttercommunity/flutter_launcher_icons#419]
Is it possible to add support for themed icons in android 13 by adding an additional monochrome icon version as a separate asset field?

**Comment by RatakondalaArun** [comment]
Posting this here for implementation reference
https://developer.android.com/develop/ui/views/launch/icon_design_adaptive

**Comment by nvi9** [comment]
I've created a [fork](https://github.com/nvi9/flutter_launcher_icons) with themed icons support, but not submitting a PR yet, since it's just a quick POC. Also, I would wait for some other (adaptive icon related, new config scheme) issues to be resolved and maybe PR #297 to be merged too, then a refactor would be needed on my code...

**Comment by Francesco-FL** [comment]
At the moment I solved it by adding the relative "monochrome" icons where the adaptive ones are, and I added this line: monochrome android:drawable="@drawable/ic_launcher_monochrome"

I hope you will update it so it will become easier

**Comment by doppio** [comment]
What needs to happen for the linked pull request to be reviewed/approved?

**Comment by And96** [comment]
> What needs to happen for the linked pull request to be reviewed/approved?

Yes. Still waiting. 1 year passed. 😵
