### ISSUE TITLE
Launcher icon on both android and ios is not changing to specified icon

### ISSUE THREAD

**Issue by newbieflutter** [fluttercommunity/flutter_launcher_icons#80]
Here is my codes in the pubspec.yaml.

flutter_icons:
  image_path: "lib/app/assets/andgreen.png"
  image_path_android: "lib/app/assets/andgreen.png"
  image_path_ios: "lib/app/assets/andgreen.png"
  android: true
  ios: true
I have tried different images too is the same. How to debug this issue cause the icon is not changing for launch? Any suggestion to debug.

**Comment by blackbeario** [comment]
Since I just went through this, I will try to help. First, make sure your indentation is correct like the README shows (that was my mistake).

Secondly, you don't need to define the `image_path` AND the android and iOS paths, if they are the same path. Just use the `image_path` like this.
```
flutter_icons:
  image_path: "lib/app/assets/andgreen.png"
  android: true
  ios: true
```
Then go through the rest of the steps in the README deliberately. If using the default `pubspec.yaml` file run this:
```
flutter packages get
flutter packages pub run flutter_launcher_icons:main
```
Finally, make sure you include your assets path correctly. Make sure to leave the trailing `/` if you don't directly name your file (you don't have to).
```
flutter:
  assets:
    - lib/app/assets/
```

**Comment by Neil-Gu** [comment]
I have same problem before, I didn't to run `flutter packages pub run flutter_launcher_icons:main` because I guess that's a command to run the ` flutter_launcher_icons:main` demo project when the first time I saw it.
